[package]
name = "erviz"
version = "0.1.0"
authors = ["Michael Zhang <failed.down@gmail.com>"]
build = "src/build.rs"

[build-dependencies]
lalrpop = "0.16"

[dependencies]
failure = "0.1"
lalrpop-util = "0.16"
regex = "1.0"
